# Uncomment the next line to define a global platform for your project


target 'DYZB' do
  # Comment the next line if you don't want to use dynamic frameworks


 platform :ios, '9.0'
 use_frameworks!

  
pod 'Alamofire', '~> 4.9.1'
pod 'Kingfisher', '~> 4.10.1'

end
